### ISSUE TITLE
Can't translate with fluents function

### ISSUE THREAD

**Issue by nisan016** [IntelligentRoboticsLabs/plansys2_tfd_plan_solver#15]
Hi, 
I tested the planner manually with a simple problem followed the instruction in README but it seems like as soon as I added a function it fail to translate the problem. I tested solving the problem online using TDF planner and it works I got a plan there. But when I trying to solve the following problem I got:

> Contains quantified condition(s): False
> Instantiating...
> Trivial rules: Converted to facts.
> Starting instantiation [16 rules]...
> Traceback (most recent call last):
>   File "/home/nisa/plansys2/TemporalFastDownward/downward/translate/translate.py", line 923, in <module>
>     sas_task = pddl_to_sas(task)
>   File "/home/nisa/plansys2/TemporalFastDownward/downward/translate/translate.py", line 784, in pddl_to_sas
>     reachable_action_params) = instantiate.explore(task)
>   File "/home/nisa/plansys2/TemporalFastDownward/downward/translate/instantiate.py", line 142, in explore
>     return instantiate(task, model)
>   File "/home/nisa/plansys2/TemporalFastDownward/downward/translate/instantiate.py", line 59, in instantiate
>     init_facts = set(task.init)  # TODO adapt
> TypeError: unhashable type: 'Assign'

my domain is looking like this:
```
(define (domain rov_domain)

(:requirements :strips :typing :fluents :durative-actions)
;; Types ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(:types
rov
location
);; end Types ;;;;;;;;;;;;;;;;;;;;;;;;;

;; Predicates ;;;;;;;;;;;;;;;;;;;;;;;;;
(:predicates
(at ?r - rov ?loc - location)
(is-armed ?r - rov)
(in-guided-mode ?r - rov)
(visited ?r - rov ?loc - location)
);; end Predicates ;;;;;;;;;;;;;;;;;;;;
;; Functions ;;;;;;;;;;;;;;;;;;;;;;;;;
(:functions
    (travel-time ?from ?to - location) - number)
;; end Functions ;;;;;;;;;;;;;;;;;;;;
;; Actions ;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(:durative-action move
    :parameters (?r - rov ?from ?to - location)
    :duration (= ?duration (travel-time ?from ?to))
    :condition (and
        (over all(is-armed ?r))
        (over all(in-guided-mode ?r))
        (at start(at ?r ?from))
        )
    :effect (and
        (at start(not(at ?r ?from)))
        (at end (visited ?r ?to))
        (at end(at ?r ?to))
    )
)

(:durative-action set-guided-mode
    :parameters (?r - rov ?loc - location)
    :duration ( = ?duration 5)
    :condition (and
        (at start(not(in-guided-mode ?r)))
        (over all(at ?r ?loc))
    )
    :effect (and
         (at end(in-guided-mode ?r))
    )
)

(:durative-action arm-rov
    :parameters (?r - rov ?loc - location)
    :duration ( = ?duration 5)
    :condition (and
        (at start(not(is-armed ?r)))
        (over all(at ?r ?loc))
    )
    :effect (and
         (at end(is-armed ?r))
    )
)
);; end Domain ;;;;;;;;;;;;;;;;;;;;;;;;
```

my problem is looking like the following: 
```

( define (problem problem1)
    ( :domain rov_domain)
    ( :objects
        loc1 loc2 - location
        rov0 - rov
    )
    ( :init
        ( at rov0 loc1 )
        (=(travel-time loc1 loc1) 0)
        (=(travel-time loc1 loc2) 50)
        (=(travel-time loc2 loc1) 50)
        (=(travel-time loc2 loc2) 0)

    )
    ( :goal
        ( and
            (visited rov0 loc2)
        )
    )
```
)

**Comment by fmrico** [comment]
Hi @nisan016 

Are you sure this is a problem with the plugin? It seems to be a problem of the planner, which is not maintained in this repo

**Comment by nisan016** [comment]
Hi,
sorry my bad. Yes, it seems to be a problem from the planner.
